<div id="owl-demo" class="owl-carousel" data-mage-init='{ "AnaRW_HomepageCarousel/js/owl": {"navigation": true, "items": 2 }}'>
    <div class="item">
        <div class="overlay">
            <h1>1</h1>
            <p>some text about image 1</p>
        </div>
        <img src="<?php echo $block->getViewFileUrl('AnaRW_HomepageCarousel::images/image1.jpg'); ?>" alt="<?php echo __('Image 1'); ?>" title="<?php echo __('Image 1'); ?>" />
    </div>
    <div class="item">
        <div class="overlay">
            <h1>2</h1>
            <p>some text about image 2</p>
        </div>
        <img src="<?php echo $block->getViewFileUrl('AnaRW_HomepageCarousel::images/image2.jpg'); ?>" alt="<?php echo __('Image 2'); ?>" title="<?php echo __('Image 2'); ?>" />
    </div>
    <div class="item">
        <div class="overlay">
            <h1>3</h1>
            <p>some text about image 3</p>
        </div>
        <img src="<?php echo $block->getViewFileUrl('AnaRW_HomepageCarousel::images/image3.jpg'); ?>" alt="<?php echo __('Image 3'); ?>" title="<?php echo __('Image 3'); ?>" />
    </div>
    <div class="item">
        <div class="overlay">
            <h1>4</h1>
            <p>some text about image 4</p>
        </div>
        <img src="<?php echo $block->getViewFileUrl('AnaRW_HomepageCarousel::images/image4.jpg'); ?>" alt="<?php echo __('Image 4'); ?>" title="<?php echo __('Image 4'); ?>" />
    </div>

</div>