<div data-mage-init='{"mage/tabs":{}}'>
    <ul>
        <li data-role="title"><a href="#tabs-1">Title 1</li>
        <li data-role="title"><a href="#tabs-2">Title 2</li>
        <li data-role="title"><a href="#tabs-3">Title 3</li>
    </ul>
    <div id="tabs-1" data-role="content">
        this is content
    </div>
    <div id="tabs-2" data-role="content">
        this is content
    </div>
    <div id="tabs-3" data-role="content">
        this is content
    </div>
</div>


